print("Hello", "World", 123, True, 3.14)
print("Hello", "World", 123, True, 3.14, sep='-')
print("Hello", "World", 123, True, 3.14, sep='#')
print("Hello", "World", 123, True, 3.14, sep='  ')
print("Hello", "World", 123, True, 3.14, sep='')
print("Hello", "World", 123, True, 3.14, sep='\n')

print("Hi, I am Venkatesh")
print("Hi, I am Venkatesh", "Doguru")
print("Hi, my name is Venkatesh", "Doguru")
print("Hi, my name is Venkatesh", "Doguru", sep=' - ')
print("Hi, my name is Venkatesh", "Doguru", sep='-')
