print("Hi", "venkatesh", "doguru")
print("Hi", "venkatesh", "doguru")
print("Hi", "venkatesh", "doguru", end='')
print("Hi", "venkatesh", "doguru")
print("Hi", "venkatesh", "doguru", end='-')
print("Hi", "venkatesh", "doguru")
print("Hi", "venkatesh", "doguru", end='\t')
print("Hi", "venkatesh", "doguru")
print("Hi", "venkatesh", "doguru", sep='-', end='\t')
print("Hi", "venkatesh", "doguru")